### ISSUE TITLE
buf-kill

### ISSUE THREAD

**Issue by hominlinx** [zilongshanren/dotfiles#1]
Hi 子龙山人，
你好，我在使用nerdtree时，加入了“ autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif ” 这样在只有一个nerdtree一个窗口时关闭vim，但我想关闭一个buffer（：bd），缺将整个vi关闭了，如何解决啊？

**Comment by andyque** [comment]
:space_invader:

**Comment by eimlfang** [comment]
你好
我想询问下，我使用了您的vim配置，在F10 编译C＋＋的时候，出现E492: not an editor command: SCCompileRun，请问compileRun是有做过修改吗？
