### ISSUE TITLE
emacs 怎么让shell显示在右边啊

### ISSUE THREAD

**Issue by yinjun322** [zilongshanren/dotfiles#4]
spacemacs shell 配置在右边好像不能设置宽度，蛋疼

(setq-default dotspacemacs-configuration-layers
  '(shell :variables
          shell-default-position 'right
          shell-default-width 30))

这个宽度好像没用啊

**Comment by zilongshanren** [comment]
```
(defvar shell-default-position 'bottom
  "Position of the shell. Possible values are `top', `bottom' and `full'.")
```

貌似不能设置width，我这边right也是可以的。
